---
# These plays are issued for common roles

# Ensure dependencies are installed
- name: Install common dependencies
  yum: name={{ item }} state=installed  # Install latest package version through yum
  with_items:
    - firewalld
    - git
    - curl
  tags:
    - packages

# Initial setup of firewalld (Open ssh port)
- name: Configure firewalld service
  firewalld:
    service: ssh
    permanent: true
    state: enabled
  notify:
    - restart fwd
  tags:
    - firewalld