---
# This playbook deploys httpd package in this site.
# NOTE: Host pool configuration is done in the hosts file

- name: apply common configuration to all nodes
  hosts: pWebserver
  roles:
    - common

- name: Deploy and configure httpd package
  hosts: pWebserver
  serial: 1     # (+) must be able to deploy without affecting customer experience (with cluster of 3 nodes or more)
  roles:
    - web